# 配置dev环境
spring:
  profiles: dev
  application:
    name: abc-eurekaServer-config

server:
  port: 8400
eureka:
  instance:
    hostname: eureka8400.com  # 指定Eureka主机
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8400.com:8400/eureka

---
# 配置test环境
spring:
  profiles: test
  application:
    name: abc-eurekaServer-config

server:
  port: 8500
eureka:
  instance:
    hostname: eureka8500.com  # 指定Eureka主机
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka