# 配置dev环境
server:
  port: 7070

spring:
  profiles: dev
  application:
    name: abcmsc-consumer-depart

eureka:
  client:
    service-url: #指定Eureka服务注册中心
      defaultZone: http://eureka8400.com:8400/eureka

# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true

---
# 配置test环境
server:
  port: 9090

spring:
  profiles: test
  application:
    name: abcmsc-consumer-depart

eureka:
  client:
    service-url: #指定Eureka服务注册中心
      defaultZone: http://eureka8500.com:8500/eureka

# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true